title: Arya Swain
logo: /assets/img/headshot_circle.png
description: |
  **Email**: [arya.m.swain@gmail.com](mailto:arya.m.swain@gmail.com)  
  **Phone**: +91 9938965594  
  **LinkedIn**: [LinkedIn Profile](https://www.linkedin.com/in/arya-swain-27518478)  
  **Resume**: [Download CV](assets/arya_ms.pdf)  
show_downloads: true
theme: jekyll-theme-minimal
